### ISSUE TITLE
Sorting got wonky after upgrading to the latest Aurelia version

### ISSUE THREAD

**Issue by Souldrinker** [aurelia/templating-resources#37]
I've been using the RubaXa/Sortable library to sort stuff in a repeat.for binding and everything has been working fine for the last month or so since I started using it, but after the 2015-04-09 release of Aurelia I started to get duplicates when I spliced the underlying array to reorder it to keep in sync with the UI.

It might be me doing something wrong in the first place that for some reason seemed to work fine anyway, or it was a bug introduced in the latest release. In any case it would be interesting to know why things changed and possibly what I should do to get it working.

I've added a more detailed description along with some code demonstrating the issue here:
https://github.com/Souldrinker/compose-issue

The exact same code works fine in aurelia-skeleton-navigation 0.11, but doesn't in 0.12.

**Comment by martingust** [comment]
@Souldrinker Will look into this.

**Comment by martingust** [comment]
@Souldrinker There was a regression here. Should be fixed in #36. Thanks for great reproduction info.

**Comment by sksbrg** [comment]
@Souldrinker can you confirm this fix has resolved the issue on your side? I can still reproduce it using version 0.13.1 of "templating-resources". My usage of "Sortable" library looks pretty similar to yours.

**Comment by Souldrinker** [comment]
Actually I haven't tested it for a while, the project I used it in is temporarily put on hold and will probably start again after the summer holidays, but I just opened it up and it seemed you're right. I'm currently on 0.13.0 of "templating-resources" there, but I do get duplicates as I did when I created this issue. 

That's odd, because I'm pretty sure I tested it soon after @martingust fixed it and that it worked then, but as you say now it seems broken again. That's too bad, because I'm just about to do some sortable stuff in the current application I'm working with and I need it working without getting duplicate views.

**Comment by martingust** [comment]
@sksbrg @souldrinker Could any of you provide steps to reproduce and I will take a look.

**Comment by Souldrinker** [comment]
Ok, I updated my sample app located at https://github.com/Souldrinker/compose-issue to the latest aurelia version and tried again and now it seems to work to drag Text1 below Text2, but if I drag the other way around (Text2 up above Text1) I still get duplicates on the screen. So it seems slightly better than the last time I reported this bug, but there is still something strange going on.

**Comment by sksbrg** [comment]
Thanks for the update!

> but if I drag the other way around (Text2 up above Text1) I still get duplicates on the screen.

Rechecked my app and can confirm that it works/breaks in the same way for me.

**Comment by jdanyow** [comment]
This may not be a workable solution with sortable, but wanted to share in case it was helpful...

With [dragula](https://bevacqua.github.io/dragula/) you can cancel the "move"- not sure if sortable has an equivalent.  Anyways, the strategy that worked for me was to use the library to get the users "drag and drop" intent, but [always cancel the move](https://github.com/jdanyow/aurelia-solitaire/blob/master/src/drag-and-drop.js#L41) and instead perform the move in the view-model so that the aurelia templating/binding system would could react the normal way and not have to worry about elements not being where they used to be.

**Comment by martingust** [comment]
@sksbrg @Souldrinker, I took a look at the sample app and it looks like the issue is what @jdanyow mentioned; that Aurelia does not know where the view's elements are since they are moved around without moving the wrapping view comments, which tells Aurelia where in the DOM a particular view is located. 

I believe though that @Souldrinker did have this working in an earlier version of Aurelia, I was quickly rolling back a few versions and it seems to work, but when looking in the DOM elements are moved out of their view comments as well, but for some reason the sorting seemed to work anyway.

This is the behavior I'm seeing:
 
On load the DOM looks like this:
```
<div id="sortableDiv">
        <!--<view>-->
        <div>Text1</div>
        <!--</view>-->
        <!--<view>-->
        <div>Text2</div>
        <!--</view>-->
        <!--anchor-->
  </div>
```
When dragging Text2 above Text1 and execution hits the `repeat` DOM looks like this (both Text1 and Text2 is inside first view comment):
```
<div id="sortableDiv">
        <!--<view>-->
        <div draggable="false" class="">
        Text2
        </div>
        <div>
        Text1
        </div>
        <!--</view>-->
        <!--<view>-->
        <!--</view>-->
        <!--anchor-->
  </div>
```
Next the `repeat` inserts a new view "Text2" at index 0 and DOM looks like:
```
<div id="sortableDiv">
       <!--<view>-->
        <div>
        Text2
        </div>
       <!--</view>-->
        <!--<view>-->
        <div draggable="false" class="">
        Text2
        </div>
        <div>
        Text1
        </div>
        <!--</view>-->
        <!--<view>-->
        <!--</view>-->
        <!--anchor-->
  </div>
```
Next the `repeat` removes view "Text2" at index 2, but in the DOM index 2 is empty  view comment and nothing but the comment gets removed.

When exiting the `repeat` the viewSlot's children is in the right order Text2 and Text1 but since Aurelia does not know where to remove the additional Text2 element it stays in the DOM. 

Not sure what the best solution to this is, or if there is a way to work with `Sortable` like @jdanyow mentioned?

**Comment by sksbrg** [comment]
Hi @martingust,

thanks for your efforts and your detailed answer. A quick search did not show me an obvious way to cancel the sort operation of Sortable. I tried to use dragula as shown by @jdanyow to sort my list but without success. I'm able to attach to the right event, I receive information about the dragged list item but I miss the information at which position it was dropped. Will dig a little bit more. Thanks once again!

**Comment by Souldrinker** [comment]
Ok, so you're pretty much saying I'm doing it wrong and I was lucky that it worked up to version 11. Well I haven't really found anything in that library, there is an open issue regarding cancelling stuff, but it doesn't seem to be worked on for now (https://github.com/RubaXa/Sortable/issues/264).

So maybe I should try to switch to another sortable library. This one seems nice, but I haven't yet had a chance to look into it more than the demo so I don't know if it supports what I want to do or if it's a good idea to use it: https://github.com/oribella/aurelia-sortable.

**Comment by martingust** [comment]
`aurelia-sortable` looks nice and embracing Aurelia. Perhaps check with @stoffeastrom what the status is. Or checkout dragula that @jdanyow was using.

**Comment by stoffeastrom** [comment]
It's actually in a quite good state. The normal use cases should work. However the aren't much documentation. I want to use the new `ìnteractive docs` that *Aurelia* will have soon.
@Souldrinker Let me know if it doesn't support what you want to do. Just send me a private im on gitter. Remember that it's a *sortable* plugin and thus have some specific *sortable* features. Another use case would be *draggable droppable* in *Aurelia* which most likely would be a own plugin.
